-- ═══════════════════════════════════════════════════════════════════════════
-- Forward Capital — briefing-led redesign, schema migration 001
--
-- Adds the tables and columns the redesigned UI reads from, and backfills them
-- from data already in the database. Every panel that previously derived its
-- content in the browser now has a column behind it:
--
--   theses.author, prediction_window_start/end   the countdown on the briefing
--   thesis_falsifiers                            "what would prove this wrong"
--   thesis_segments                              legs of the thesis + the gap
--   thesis_milestones                            the prediction timeline
--   thesis_confidence_history                    the confidence trend line
--   thesis_assumptions.signal_categories         the assumption ledger
--   sources.description/status/requires_key      the reliability table
--   company_quotes, company_analyst_consensus    watchlist + company pages
--
-- Safe to run more than once: every statement is IF NOT EXISTS / ON CONFLICT /
-- guarded by a WHERE. It does not drop or rewrite any existing column.
--
-- Run it in the Supabase SQL editor, or:
--   psql "$SUPABASE_DB_URL" -f scripts/migrations/001_redesign_schema.sql
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

-- ───────────────────────────────────────────────────────────────────────────
-- 1. New columns on existing tables
-- ───────────────────────────────────────────────────────────────────────────

ALTER TABLE theses
  ADD COLUMN IF NOT EXISTS author                  text,
  ADD COLUMN IF NOT EXISTS prediction_window_start text,
  ADD COLUMN IF NOT EXISTS prediction_window_end   text;

COMMENT ON COLUMN theses.prediction_window_start IS
  'ISO date (YYYY-MM-DD). The window the prediction resolves in; drives the countdown.';
COMMENT ON COLUMN theses.prediction_window_end IS
  'ISO date (YYYY-MM-DD), inclusive. NULL on either side hides the countdown rather than inventing one.';

-- NULL means "not tracked by category" and the ledger says so. An empty array
-- means the thesis calls for it but no category exists to hold it yet — which
-- is a real finding, and shows as a hard zero.
ALTER TABLE thesis_assumptions
  ADD COLUMN IF NOT EXISTS signal_categories text;

COMMENT ON COLUMN thesis_assumptions.signal_categories IS
  'JSON array of signals.signal_category values that supply evidence for this assumption, e.g. ["patent_filing"].';

ALTER TABLE sources
  ADD COLUMN IF NOT EXISTS description  text,
  ADD COLUMN IF NOT EXISTS status       text    NOT NULL DEFAULT 'connected',
  ADD COLUMN IF NOT EXISTS requires_key boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN sources.status IS 'connected | needs_key | not_connected';

-- ───────────────────────────────────────────────────────────────────────────
-- 2. New tables
-- ───────────────────────────────────────────────────────────────────────────

-- What would prove the thesis wrong. Rows, so they can be revised as the
-- thesis is tested, rather than copy baked into a component.
CREATE TABLE IF NOT EXISTS thesis_falsifiers (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thesis_id  bigint  NOT NULL REFERENCES theses (id) ON DELETE CASCADE,
  "text"     text    NOT NULL,
  sort_order integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS thesis_falsifiers_thesis_idx ON thesis_falsifiers (thesis_id, sort_order);

-- The legs the thesis rests on. A leg with zero companies is a research gap the
-- UI holds open — is_thesis_leg = false marks segments the narrative names but
-- does not bet on, which are excluded from segment scoring.
CREATE TABLE IF NOT EXISTS thesis_segments (
  id            bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thesis_id     bigint  NOT NULL REFERENCES theses (id) ON DELETE CASCADE,
  name          text    NOT NULL,
  note          text    NOT NULL DEFAULT '',
  is_thesis_leg boolean NOT NULL DEFAULT true,
  sort_order    integer NOT NULL DEFAULT 0,
  CONSTRAINT thesis_segments_unique_name UNIQUE (thesis_id, name)
);
CREATE INDEX IF NOT EXISTS thesis_segments_thesis_idx ON thesis_segments (thesis_id, sort_order);

-- Checkpoints inside the prediction window. A NULL due_date is meaningful: it
-- marks work that is blocking with no date attached to it.
CREATE TABLE IF NOT EXISTS thesis_milestones (
  id         bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thesis_id  bigint  NOT NULL REFERENCES theses (id) ON DELETE CASCADE,
  title      text    NOT NULL,
  detail     text    NOT NULL DEFAULT '',
  due_date   text,
  status     text    NOT NULL DEFAULT 'scheduled',
  sort_order integer NOT NULL DEFAULT 0,
  CONSTRAINT thesis_milestones_status_check
    CHECK (status IN ('scheduled', 'blocking', 'closes', 'done'))
);
CREATE INDEX IF NOT EXISTS thesis_milestones_thesis_idx ON thesis_milestones (thesis_id, sort_order);

-- One row per recompute, so the trend line is a record of what the score
-- actually read rather than a reconstruction from current signals.
CREATE TABLE IF NOT EXISTS thesis_confidence_history (
  id           bigint           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thesis_id    bigint           NOT NULL REFERENCES theses (id) ON DELETE CASCADE,
  confidence   double precision NOT NULL,
  gauge        integer          NOT NULL,
  signal_count integer          NOT NULL DEFAULT 0,
  computed_at  text             NOT NULL
);
CREATE INDEX IF NOT EXISTS thesis_confidence_history_thesis_idx
  ON thesis_confidence_history (thesis_id, computed_at DESC);

-- Latest market snapshot per company, denormalised out of signals.raw_payload
-- so the watchlist can read prices without parsing JSON in the browser. The
-- signal still carries the provenance; this is the queryable copy.
CREATE TABLE IF NOT EXISTS company_quotes (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id         bigint NOT NULL UNIQUE REFERENCES companies (id) ON DELETE CASCADE,
  source_id          bigint REFERENCES sources (id) ON DELETE SET NULL,
  price              double precision,
  "change"           double precision,
  changes_percentage double precision,
  market_cap         double precision,
  pe                 double precision,
  volume             double precision,
  year_low           double precision,
  year_high          double precision,
  as_of              text NOT NULL
);

CREATE TABLE IF NOT EXISTS company_analyst_consensus (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id          bigint NOT NULL UNIQUE REFERENCES companies (id) ON DELETE CASCADE,
  source_id           bigint REFERENCES sources (id) ON DELETE SET NULL,
  rating              text,
  total_ratings       integer,
  bullish_pct         double precision,
  neutral_pct         double precision,
  bearish_pct         double precision,
  avg_price_target    double precision,
  median_price_target double precision,
  high_price_target   double precision,
  low_price_target    double precision,
  note                text,
  as_of               text NOT NULL
);

-- ───────────────────────────────────────────────────────────────────────────
-- 3. Backfill — existing rows only. Nothing here invents evidence.
-- ───────────────────────────────────────────────────────────────────────────

-- 3a. Prediction window, read out of the prediction sentence the author wrote.
--     Only fills rows that don't already have a window set by hand.
UPDATE theses SET
  prediction_window_start = CASE
    WHEN prediction ~* '\mH1\s*[0-9]{4}\M' THEN substring(prediction from '\mH1\s*([0-9]{4})\M') || '-01-01'
    WHEN prediction ~* '\mH2\s*[0-9]{4}\M' THEN substring(prediction from '\mH2\s*([0-9]{4})\M') || '-07-01'
  END,
  prediction_window_end = CASE
    WHEN prediction ~* '\mH1\s*[0-9]{4}\M' THEN substring(prediction from '\mH1\s*([0-9]{4})\M') || '-06-30'
    WHEN prediction ~* '\mH2\s*[0-9]{4}\M' THEN substring(prediction from '\mH2\s*([0-9]{4})\M') || '-12-31'
  END
WHERE prediction_window_start IS NULL
  AND prediction ~* '\mH[12]\s*[0-9]{4}\M';

UPDATE theses SET author = 'Forward Capital' WHERE author IS NULL;

-- 3b. Source copy: why each source carries the weight it carries.
UPDATE sources SET description = v.description, status = v.status, requires_key = v.requires_key
FROM (VALUES
  ('sec_edgar',
   'Primary-source filings. Highest weight in the model — nothing else here is a legal document.',
   'connected', false),
  ('finance',
   'Quotes, insider transactions and analyst research. Reachable only from an agent session, so a scheduled task pushes it in over HTTPS.',
   'connected', false),
  ('uspto_patentsview',
   'Free to register. Blocking one of the signal types the thesis explicitly calls for.',
   'needs_key', true),
  ('manual_research_inbox',
   'Human-typed notes. Deliberately weighted lowest — a claim you heard is not a filing you read.',
   'connected', false),
  ('similarweb_premium_data',
   'Web-traffic and product-usage signals. Connector-backed, synced per company on request.',
   'not_connected', false),
  ('cbinsights_mcp_cashmere',
   'Market and company research. Connector-backed, not part of the scheduled refresh.',
   'not_connected', false),
  ('statista_mcp_cashmere',
   'Market-size and industry statistics. Connector-backed, not part of the scheduled refresh.',
   'not_connected', false)
) AS v (source_identifier, description, status, requires_key)
WHERE sources.source_identifier = v.source_identifier
  AND sources.description IS NULL;

-- 3c. Which signal categories can supply evidence for each stated requirement.
--     '[]' is deliberate for X/Twitter: the thesis calls for it and the signal
--     taxonomy has no category to hold it, so it can never accumulate evidence.
--     NULL is left in place for assumptions no category tracks at all.
UPDATE thesis_assumptions SET signal_categories = v.categories
FROM (VALUES
  ('%tracking: Patent filings%',                                   '["patent_filing"]'),
  ('%tracking: Supplier / customer partnership announcements%',    '["partnership_or_supply_chain"]'),
  ('%tracking: Government contracts, grants, and policy actions%', '["regulatory_filing","macro_indicator"]'),
  ('%tracking: Web traffic / product usage signals%',              '["web_traffic_signal"]'),
  ('%tracking: X/Twitter posts%',                                  '[]'),
  ('%priced in%',                                                  '["analyst_action","price_action"]')
) AS v (pattern, categories)
WHERE thesis_assumptions.signal_categories IS NULL
  AND thesis_assumptions."text" ILIKE v.pattern;

-- 3d. Falsification conditions.
INSERT INTO thesis_falsifiers (thesis_id, "text", sort_order)
SELECT t.id, v."text", v.sort_order
FROM theses t
CROSS JOIN (VALUES
  ('Materials-exposed names re-rate before Jul 2026 — the call is late, not early.', 0),
  ('The supply constraint resolves in silicon, not materials — capacity additions clear the bottleneck.', 1),
  ('Consensus targets on Power and Networking stay flat through Dec 2026 despite demand.', 2)
) AS v ("text", sort_order)
WHERE t.status = 'active'
  AND NOT EXISTS (SELECT 1 FROM thesis_falsifiers f WHERE f.thesis_id = t.id);

-- 3e. Segments. The four legs the thesis names, then every other segment
--     already present on companies, recorded as context rather than a leg.
INSERT INTO thesis_segments (thesis_id, name, note, is_thesis_leg, sort_order)
SELECT t.id, v.name, v.note, true, v.sort_order
FROM theses t
CROSS JOIN (VALUES
  ('Chips',
   'AI accelerators and general-purpose semiconductors that power AI training/inference.', 0),
  ('Strategic materials',
   'No companies identified yet — this is the thesis''s core unproven bet. Add candidates via Research Inbox.', 1),
  ('Power',
   'Power generation and cooling infrastructure for AI data centers.', 2),
  ('Networking',
   'Interconnect, ASIC, and networking silicon for AI clusters.', 3)
) AS v (name, note, sort_order)
WHERE t.status = 'active'
ON CONFLICT (thesis_id, name) DO NOTHING;

INSERT INTO thesis_segments (thesis_id, name, note, is_thesis_leg, sort_order)
SELECT t.id,
       c.segment,
       'Context only. Named in the thesis narrative, excluded from segment scoring.',
       false,
       100 + row_number() OVER (ORDER BY c.segment)
FROM theses t
CROSS JOIN (SELECT DISTINCT segment FROM companies WHERE segment IS NOT NULL) c
WHERE t.status = 'active'
ON CONFLICT (thesis_id, name) DO NOTHING;

-- 3f. Milestones: window opens, each uncovered leg, window closes.
INSERT INTO thesis_milestones (thesis_id, title, detail, due_date, status, sort_order)
SELECT t.id, 'Window opens', 'evidence retrieved from here counts inside the window',
       t.prediction_window_start, 'scheduled', 0
FROM theses t
WHERE t.status = 'active'
  AND t.prediction_window_start IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM thesis_milestones m WHERE m.thesis_id = t.id);

INSERT INTO thesis_milestones (thesis_id, title, detail, due_date, status, sort_order)
SELECT s.thesis_id, s.name || ' names identified', 'no date — blocking the core bet',
       NULL, 'blocking', 1
FROM thesis_segments s
WHERE s.is_thesis_leg
  AND NOT EXISTS (SELECT 1 FROM companies c WHERE c.segment = s.name)
  AND NOT EXISTS (
    SELECT 1 FROM thesis_milestones m
    WHERE m.thesis_id = s.thesis_id AND m.title = s.name || ' names identified'
  );

INSERT INTO thesis_milestones (thesis_id, title, detail, due_date, status, sort_order)
SELECT t.id, 'Window closes', 'thesis resolves either way', t.prediction_window_end, 'closes', 2
FROM theses t
WHERE t.status = 'active'
  AND t.prediction_window_end IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM thesis_milestones m WHERE m.thesis_id = t.id AND m.status = 'closes');

-- 3g. Market snapshots, lifted out of the JSON already stored on signals.
--     DISTINCT ON keeps the newest price_action row per company.
INSERT INTO company_quotes (
  company_id, source_id, price, "change", changes_percentage,
  market_cap, pe, volume, year_low, year_high, as_of
)
SELECT DISTINCT ON (s.company_id)
  s.company_id,
  s.source_id,
  (s.raw_payload::jsonb ->> 'price')::double precision,
  (s.raw_payload::jsonb ->> 'change')::double precision,
  (s.raw_payload::jsonb ->> 'changesPercentage')::double precision,
  (s.raw_payload::jsonb ->> 'marketCap')::double precision,
  (s.raw_payload::jsonb ->> 'pe')::double precision,
  (s.raw_payload::jsonb ->> 'volume')::double precision,
  (s.raw_payload::jsonb ->> 'yearLow')::double precision,
  (s.raw_payload::jsonb ->> 'yearHigh')::double precision,
  COALESCE(s.raw_payload::jsonb ->> 'as_of', s.retrieved_at)
FROM signals s
WHERE s.signal_category = 'price_action'
  AND s.company_id IS NOT NULL
  AND s.raw_payload IS NOT NULL
  AND left(btrim(s.raw_payload), 1) = '{'
  AND (s.raw_payload::jsonb ->> 'price') IS NOT NULL
ORDER BY s.company_id, s.retrieved_at DESC
ON CONFLICT (company_id) DO NOTHING;

INSERT INTO company_analyst_consensus (
  company_id, source_id, rating, total_ratings, bullish_pct, neutral_pct, bearish_pct,
  avg_price_target, median_price_target, high_price_target, low_price_target, note, as_of
)
SELECT DISTINCT ON (s.company_id)
  s.company_id,
  s.source_id,
  s.raw_payload::jsonb ->> 'rating',
  (s.raw_payload::jsonb ->> 'total_ratings')::integer,
  (s.raw_payload::jsonb ->> 'bullish_pct')::double precision,
  (s.raw_payload::jsonb ->> 'neutral_pct')::double precision,
  (s.raw_payload::jsonb ->> 'bearish_pct')::double precision,
  (s.raw_payload::jsonb ->> 'avg_price_target')::double precision,
  (s.raw_payload::jsonb ->> 'median_price_target')::double precision,
  (s.raw_payload::jsonb ->> 'high_price_target')::double precision,
  (s.raw_payload::jsonb ->> 'low_price_target')::double precision,
  s.raw_payload::jsonb ->> 'note',
  s.retrieved_at
FROM signals s
WHERE s.signal_category = 'analyst_action'
  AND s.title ILIKE '%analyst consensus%'
  AND s.company_id IS NOT NULL
  AND s.raw_payload IS NOT NULL
  AND left(btrim(s.raw_payload), 1) = '{'
  AND (s.raw_payload::jsonb ->> 'total_ratings') IS NOT NULL
ORDER BY s.company_id, s.retrieved_at DESC
ON CONFLICT (company_id) DO NOTHING;

-- 3h. Seed the trend line with the score as it stands right now. This is the
--     one real reading available — past values were never recorded, and are
--     not fabricated here. The line starts after the next recompute.
INSERT INTO thesis_confidence_history (thesis_id, confidence, gauge, signal_count, computed_at)
SELECT t.id,
       t.confidence_score,
       round(greatest(-1, least(1, t.confidence_score)) * 100)::integer,
       (SELECT count(*) FROM signals s WHERE s.thesis_id = t.id),
       COALESCE(NULLIF(t.updated_at, ''), to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'))
FROM theses t
WHERE t.confidence_score IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM thesis_confidence_history h WHERE h.thesis_id = t.id);

COMMIT;

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. Row-level security
--
-- The app connects with the Supabase anon key, so the new tables must be
-- reachable the same way the existing ones are. Check what you already have:
--
--   SELECT relname, relrowsecurity
--   FROM pg_class
--   WHERE relname IN ('signals','theses','company_quotes','thesis_segments');
--
-- If relrowsecurity is false on your existing tables, RLS is off and the new
-- tables are already consistent — nothing to do. If it is true, the block
-- below mirrors a permissive single-user setup onto the new tables. Read it
-- before running it: it grants the anon role full access, which is only
-- appropriate for a personal single-user instance.
-- ═══════════════════════════════════════════════════════════════════════════

-- DO $$
-- DECLARE t text;
-- BEGIN
--   FOREACH t IN ARRAY ARRAY[
--     'thesis_falsifiers', 'thesis_segments', 'thesis_milestones',
--     'thesis_confidence_history', 'company_quotes', 'company_analyst_consensus'
--   ] LOOP
--     EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
--     EXECUTE format(
--       'CREATE POLICY %I ON %I FOR ALL TO anon USING (true) WITH CHECK (true)',
--       t || '_anon_all', t
--     );
--   END LOOP;
-- END $$;

-- ═══════════════════════════════════════════════════════════════════════════
-- 5. Rollback
--
-- Drops everything this migration added. The added columns are dropped too, so
-- take a backup first if any of them have been edited by hand.
-- ═══════════════════════════════════════════════════════════════════════════

-- BEGIN;
-- DROP TABLE IF EXISTS company_analyst_consensus;
-- DROP TABLE IF EXISTS company_quotes;
-- DROP TABLE IF EXISTS thesis_confidence_history;
-- DROP TABLE IF EXISTS thesis_milestones;
-- DROP TABLE IF EXISTS thesis_segments;
-- DROP TABLE IF EXISTS thesis_falsifiers;
-- ALTER TABLE sources            DROP COLUMN IF EXISTS requires_key,
--                                DROP COLUMN IF EXISTS status,
--                                DROP COLUMN IF EXISTS description;
-- ALTER TABLE thesis_assumptions DROP COLUMN IF EXISTS signal_categories;
-- ALTER TABLE theses             DROP COLUMN IF EXISTS prediction_window_end,
--                                DROP COLUMN IF EXISTS prediction_window_start,
--                                DROP COLUMN IF EXISTS author;
-- COMMIT;
